### PR TITLE
Ensure sitemap.xml does not show drafts

### PR DESCRIPTION
**Pull request by DeonHeyns**
If you have any drafts in your _posts folder they will be added to the sitemap and potentially indexed by the bots

### CODE REVIEW

**Comment by holman** [comment]
Looks like there's some merge conflicts with this, but good catch! Fix 'em up and I'll merge it.

**Comment by DeonHeyns** [comment]
Sorry about that @holman merge conflict fixed!

**Comment by holman** [comment]
Wait, do I not have a sitemap currently?

**Comment by DeonHeyns** [comment]
Interesting I see it in my fork on master but not in the gh-pages on the main left repo.

**Comment by holman** [comment]
Ah, right: #27. I'm not sure it takes into account drafts, though. Maybe send a pull to that repo?

**Comment by DeonHeyns** [comment]
Sure thing makes sense, will send a PR to [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap)

**Pull request closed without merging**
